# Generated by Django 5.2.1 on 2025-05-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='PurchaseRequest',
        ),
    ]
